### ISSUE TITLE
Send ejection presence to all members of Gateway MUCs when shutting down the bridge

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-bifrost#136]
Which should help to alleviate state issues where the xmpp client becomes confused

**Comment by ge0rg** [comment]
That sounds like a good short-term solution(*).

When removing a user due to a bridge shutdown, you should have the status codes 110 (user's own presence) and 333 (technical reasons as opposed to a kick or a user's decision to leave), in the kick presence:

```xml
<presence
    from='chatroom@bridge/nickname'
    to='user@domain/resource'
    type='unavailable'>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <item affiliation='none' role='none' />
    <status code='110'/>
    <status code='333'/>
  </x>
</presence>
```

(*) Prosody has adopted an approach of persisting room membership over restarts, so that a short downtime, e.g. caused by an upgrade, won't be noticeable to users. However, there are also issues with that, e.g. due to the user's server sending back an error when a user tried to send a message.

**Comment by Half-Shot** [comment]
So for now, I've *fixed* it so that restarting will not kick XMPP users at all on reconnect.

**Comment by Half-Shot** [comment]
We now persist devices in the database as of #176, so in theory this all works now.
