### ISSUE TITLE
Time to review/merge PRs and look Issues?

### ISSUE THREAD

**Issue by Neustradamus** [matrix-org/matrix-bifrost#306]
Dear @matrix-org team, @Half-Shot,

I wish you a Happy New Year 2022!

I think it is time to review/merge PRs (to remove bugs or add improvements) of this repository.

It will permit to enter in the future, we are in 2022.

You can look here:
- https://github.com/matrix-org/matrix-bifrost/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

Issues are here:
- https://github.com/matrix-org/matrix-bifrost/issues

Thanks in advance.

**Comment by Half-Shot** [comment]
@Neustradamus Thanks, but we're well aware of how to use GitHub. The team is unfortunately spread a bit thin, and so some of these PRs are taking longer to get to. Please don't ping the team or myself over issues like these, because they aren't constructive and won't get things looked at any quicker.

I'm going to close and lock this discussion.
