### ISSUE TITLE
use different disco#info identity type (e.g. type='matrix')

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-bifrost#48]
so that folks like search.jabber.network who don't want to list matrix rooms can do so

**Comment by horazont** [comment]
Hi, search.jabber.network developer and operator here.

This is not necessarily about permanent removal. I want to have a clear indicator of a service being a bridge, because bridges may inherently cause duplication and we need to be able to deal with that.

Although I’ll be clear that this change will stop Matrix bridges from being listed by search.jabber.network without code changes.

I think for the bridge/gateway usecase, it might be more useful to have a dedicated directory of bridge services (which I am happy to host there, I’ve started to work on a directory for IRC gateways already).

If there is user demand, I can also see offering the option to also search XMPP-joinable matrix rooms via search.jabber.network down the road.

**Comment by ge0rg** [comment]
@horazont could you clarify whether the bridge **must not** advertise `conference/text`, or if it is sufficient to advertise **both** `conference/text` and `gateway/matrix`. The semantics in https://xmpp.org/registrar/disco-categories.html#conference are not really clear for non-IRC bridges ;)

**Comment by horazont** [comment]
Given that prior art, I would expect conference/matrix. Currently, s.j.n would trigger on conference/text, because it does not interpret the other identities.

However, from a purity point of view, conference/text+gateway/matrix would be nicer.

**Comment by Half-Shot** [comment]
#138 should have improved the situation
